export interface MaterialConfig {
  name: string;
  type: "METAL" | "GEMSTONE";
  color: string;
  metallic: number;
  roughness: number;
  ior: number;
  transmission: number;
  clearcoat: number;
  opacity: number;
  envMapIntensity: number;
}

export const METAL_PRESETS: MaterialConfig[] = [
  {
    name: "Yellow Gold",
    type: "METAL",
    color: "#FFD700",
    metallic: 1.0,
    roughness: 0.15,
    ior: 1.5,
    transmission: 0,
    clearcoat: 0.1,
    opacity: 1,
    envMapIntensity: 1.5,
  },
  {
    name: "White Gold",
    type: "METAL",
    color: "#E8E8E0",
    metallic: 1.0,
    roughness: 0.12,
    ior: 1.5,
    transmission: 0,
    clearcoat: 0.1,
    opacity: 1,
    envMapIntensity: 1.5,
  },
  {
    name: "Rose Gold",
    type: "METAL",
    color: "#E8A090",
    metallic: 1.0,
    roughness: 0.15,
    ior: 1.5,
    transmission: 0,
    clearcoat: 0.1,
    opacity: 1,
    envMapIntensity: 1.5,
  },
  {
    name: "Sterling Silver",
    type: "METAL",
    color: "#C0C0C0",
    metallic: 1.0,
    roughness: 0.1,
    ior: 1.5,
    transmission: 0,
    clearcoat: 0.15,
    opacity: 1,
    envMapIntensity: 1.8,
  },
  {
    name: "Platinum",
    type: "METAL",
    color: "#E5E4E2",
    metallic: 1.0,
    roughness: 0.08,
    ior: 1.5,
    transmission: 0,
    clearcoat: 0.2,
    opacity: 1,
    envMapIntensity: 2.0,
  },
  {
    name: "Copper",
    type: "METAL",
    color: "#B87333",
    metallic: 1.0,
    roughness: 0.2,
    ior: 1.5,
    transmission: 0,
    clearcoat: 0.05,
    opacity: 1,
    envMapIntensity: 1.3,
  },
  {
    name: "Bronze",
    type: "METAL",
    color: "#CD7F32",
    metallic: 1.0,
    roughness: 0.25,
    ior: 1.5,
    transmission: 0,
    clearcoat: 0.05,
    opacity: 1,
    envMapIntensity: 1.2,
  },
];

export const GEMSTONE_PRESETS: MaterialConfig[] = [
  {
    name: "Diamond",
    type: "GEMSTONE",
    color: "#F0F0FF",
    metallic: 0,
    roughness: 0.0,
    ior: 2.42,
    transmission: 0.95,
    clearcoat: 1.0,
    opacity: 0.1,
    envMapIntensity: 3.0,
  },
  {
    name: "Ruby",
    type: "GEMSTONE",
    color: "#E0115F",
    metallic: 0,
    roughness: 0.05,
    ior: 1.77,
    transmission: 0.7,
    clearcoat: 1.0,
    opacity: 0.3,
    envMapIntensity: 2.5,
  },
  {
    name: "Sapphire",
    type: "GEMSTONE",
    color: "#0F52BA",
    metallic: 0,
    roughness: 0.05,
    ior: 1.77,
    transmission: 0.7,
    clearcoat: 1.0,
    opacity: 0.3,
    envMapIntensity: 2.5,
  },
  {
    name: "Emerald",
    type: "GEMSTONE",
    color: "#50C878",
    metallic: 0,
    roughness: 0.08,
    ior: 1.58,
    transmission: 0.6,
    clearcoat: 0.8,
    opacity: 0.4,
    envMapIntensity: 2.0,
  },
  {
    name: "Amethyst",
    type: "GEMSTONE",
    color: "#9966CC",
    metallic: 0,
    roughness: 0.05,
    ior: 1.55,
    transmission: 0.75,
    clearcoat: 0.9,
    opacity: 0.25,
    envMapIntensity: 2.2,
  },
  {
    name: "Topaz",
    type: "GEMSTONE",
    color: "#FFC87C",
    metallic: 0,
    roughness: 0.03,
    ior: 1.63,
    transmission: 0.8,
    clearcoat: 0.9,
    opacity: 0.2,
    envMapIntensity: 2.3,
  },
  {
    name: "Opal",
    type: "GEMSTONE",
    color: "#A8C3BC",
    metallic: 0.1,
    roughness: 0.15,
    ior: 1.45,
    transmission: 0.3,
    clearcoat: 0.5,
    opacity: 0.6,
    envMapIntensity: 1.8,
  },
  {
    name: "Pearl",
    type: "GEMSTONE",
    color: "#FDEEF4",
    metallic: 0.3,
    roughness: 0.3,
    ior: 1.53,
    transmission: 0,
    clearcoat: 0.8,
    opacity: 1,
    envMapIntensity: 1.5,
  },
];

export const ALL_PRESETS = [...METAL_PRESETS, ...GEMSTONE_PRESETS];
